import type { Category, Character } from "@/types";

export const APP_NAME = "IslamiToons";
export const APP_TAGLINE = "بچوں کے لیے اسلامی کارٹون دنیا";
export const APP_TAGLINE_EN = "Islamic Cartoon World for Children";
export const APP_URL = "https://islamitoons.onspace.app";

export const CATEGORIES: Category[] = [
  {
    id: "islamic",
    name: "Islamic Stories",
    nameUrdu: "اسلامی کہانیاں",
    description: "Stories of Prophets, Companions and Islamic values",
    descriptionUrdu: "انبیاء، صحابہ اور اسلامی اقدار کی کہانیاں",
    icon: "🕌",
    gradient: "from-green-600 to-emerald-500",
    bgClass: "gradient-hero",
    count: 24,
  },
  {
    id: "historical",
    name: "Historical Tales",
    nameUrdu: "تاریخی نوادرات",
    description: "Great moments from Islamic history and civilization",
    descriptionUrdu: "اسلامی تاریخ اور تہذیب کے عظیم لمحات",
    icon: "📜",
    gradient: "from-amber-600 to-yellow-500",
    bgClass: "gradient-gold",
    count: 18,
  },
  {
    id: "jungle",
    name: "Jungle Adventures",
    nameUrdu: "جنگل کی مہم جوئی",
    description: "Exciting jungle stories with talking animals",
    descriptionUrdu: "بولنے والے جانوروں کے ساتھ دلچسپ جنگل کی کہانیاں",
    icon: "🦁",
    gradient: "from-green-700 to-lime-600",
    bgClass: "gradient-jungle",
    count: 15,
  },
  {
    id: "comedy",
    name: "Comedy & Fun",
    nameUrdu: "مزاحیہ انٹرٹینمنٹ",
    description: "Notu-Putlu style funny and wholesome cartoons",
    descriptionUrdu: "نوتو پتلو اسٹائل مزاحیہ اور صالح کارٹونز",
    icon: "😄",
    gradient: "from-orange-500 to-pink-500",
    bgClass: "gradient-gold",
    count: 20,
  },
  {
    id: "outdoor",
    name: "Outdoor Activities",
    nameUrdu: "آؤٹ ڈور سرگرمیاں",
    description: "Sports, nature exploration and healthy living",
    descriptionUrdu: "کھیل، قدرت کی دریافت اور صحت مند زندگی",
    icon: "⚽",
    gradient: "from-sky-500 to-cyan-500",
    bgClass: "gradient-sky",
    count: 12,
  },
  {
    id: "moral",
    name: "Moral Stories",
    nameUrdu: "سبق آموز کہانیاں",
    description: "Life lessons, kindness, honesty and character",
    descriptionUrdu: "زندگی کے سبق، مہربانی، ایمانداری اور کردار",
    icon: "💡",
    gradient: "from-violet-600 to-purple-500",
    bgClass: "gradient-hero",
    count: 22,
  },
  {
    id: "notu-putlu",
    name: "Notu & Putlu",
    nameUrdu: "نوتو اور پتلو",
    description: "Adventures of two best friends - Notu and Putlu",
    descriptionUrdu: "دو بہترین دوستوں نوتو اور پتلو کی مہم جوئی",
    icon: "👦",
    gradient: "from-rose-500 to-red-400",
    bgClass: "gradient-gold",
    count: 16,
  },
];

export const CHARACTERS: Character[] = [
  {
    id: "notu",
    name: "Notu",
    nameUrdu: "نوتو",
    emoji: "👦",
    description: "A curious and brave young boy",
    descriptionUrdu: "ایک متجسس اور بہادر نوجوان لڑکا",
    color: "bg-orange-100 border-orange-400",
    category: "notu-putlu",
  },
  {
    id: "putlu",
    name: "Putlu",
    nameUrdu: "پتلو",
    emoji: "👧",
    description: "Notu's clever and kind best friend",
    descriptionUrdu: "نوتو کی ذہین اور مہربان بہترین دوست",
    color: "bg-pink-100 border-pink-400",
    category: "notu-putlu",
  },
  {
    id: "lion",
    name: "Leo the Lion",
    nameUrdu: "شیر لیو",
    emoji: "🦁",
    description: "The wise and just king of the jungle",
    descriptionUrdu: "جنگل کا عقلمند اور منصف بادشاہ",
    color: "bg-yellow-100 border-yellow-500",
    category: "jungle",
  },
  {
    id: "parrot",
    name: "Tota the Parrot",
    nameUrdu: "طوطا",
    emoji: "🦜",
    description: "A colorful parrot who loves poetry",
    descriptionUrdu: "ایک رنگ برنگا طوطا جو شاعری سے محبت کرتا ہے",
    color: "bg-green-100 border-green-500",
    category: "jungle",
  },
  {
    id: "scholar",
    name: "Maulana Sahab",
    nameUrdu: "مولانا صاحب",
    emoji: "👳",
    description: "A wise Islamic scholar who guides children",
    descriptionUrdu: "ایک عقلمند اسلامی عالم جو بچوں کی رہنمائی کرتے ہیں",
    color: "bg-emerald-100 border-emerald-500",
    category: "islamic",
  },
  {
    id: "elephant",
    name: "Hathi",
    nameUrdu: "ہاتھی",
    emoji: "🐘",
    description: "The gentle giant who remembers everything",
    descriptionUrdu: "نرم دل دیو جو سب کچھ یاد رکھتا ہے",
    color: "bg-gray-100 border-gray-400",
    category: "jungle",
  },
  {
    id: "princess",
    name: "Princess Noor",
    nameUrdu: "شہزادی نور",
    emoji: "👸",
    description: "A brave princess with strong faith",
    descriptionUrdu: "مضبوط ایمان والی ایک بہادر شہزادی",
    color: "bg-violet-100 border-violet-400",
    category: "historical",
  },
  {
    id: "adventurer",
    name: "Explorer Bilal",
    nameUrdu: "مہم جو بلال",
    emoji: "🧭",
    description: "An adventurous boy who loves nature",
    descriptionUrdu: "ایک مہم جو لڑکا جو فطرت سے محبت کرتا ہے",
    color: "bg-sky-100 border-sky-400",
    category: "outdoor",
  },
];

export const SETTINGS = [
  { value: "masjid", label: "Masjid / مسجد", emoji: "🕌" },
  { value: "jungle", label: "Jungle / جنگل", emoji: "🌿" },
  { value: "desert", label: "Desert / صحرا", emoji: "🏜️" },
  { value: "garden", label: "Garden / باغیچہ", emoji: "🌸" },
  { value: "school", label: "School / مدرسہ", emoji: "🏫" },
  { value: "sea", label: "Sea / سمندر", emoji: "🌊" },
  { value: "mountain", label: "Mountain / پہاڑ", emoji: "⛰️" },
  { value: "village", label: "Village / گاؤں", emoji: "🏘️" },
  { value: "city", label: "City / شہر", emoji: "🏙️" },
  { value: "space", label: "Space / خلاء", emoji: "🌙" },
];

export const THEMES = [
  { value: "honesty", label: "Honesty / ایمانداری" },
  { value: "kindness", label: "Kindness / مہربانی" },
  { value: "courage", label: "Courage / بہادری" },
  { value: "friendship", label: "Friendship / دوستی" },
  { value: "prayer", label: "Prayer / نماز" },
  { value: "sharing", label: "Sharing / دوسروں کو دینا" },
  { value: "patience", label: "Patience / صبر" },
  { value: "gratitude", label: "Gratitude / شکرگزاری" },
  { value: "respect", label: "Respect / احترام" },
  { value: "adventure", label: "Adventure / مہم جوئی" },
  { value: "curiosity", label: "Curiosity / تجسس" },
  { value: "creativity", label: "Creativity / تخلیقیت" },
];

export const LESSONS_URDU: Record<string, string> = {
  honesty: "ہمیشہ سچ بولنا چاہیے",
  kindness: "ہر کسی کے ساتھ مہربانی کرو",
  courage: "ڈرو نہیں، اللہ پر بھروسہ رکھو",
  friendship: "اچھا دوست قیمتی خزانہ ہے",
  prayer: "نماز زندگی کا نور ہے",
  sharing: "دوسروں کو دینے میں خوشی ہے",
  patience: "صبر کا پھل میٹھا ہوتا ہے",
  gratitude: "اللہ کا شکر ادا کرو",
  respect: "بڑوں کا احترام کرو",
  adventure: "نئی چیزیں سیکھنے سے نہ گھبراؤ",
  curiosity: "سوال پوچھنا علم کی کنجی ہے",
  creativity: "اپنی تخلیقی صلاحیتیں استعمال کرو",
};
